services:
 accounts:
  image: "senharshit03/accounts:img1"
  container_name: accounts_ms
  ports:
   - "8081:8081"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
   - piggybank


 loans:
  image: "senharshit03/loans:img1"
  container_name: loans_ms
  ports:
   - "8090:8090"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
     - piggybank

 cards:
  image: "senharshit03/cards:img1"
  container_name: cards_ms
  ports:
   - "9000:9000"
  deploy:
   resources:
    limits:
     memory: 700m
  networks:
     - piggybank


networks:
 piggybank:
  driver: "bridge"