server:
  port: 8090

spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

#  sql:
#    init:
#      mode: always
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "loans"
    description: "Loan service for Piggy Bank"
    version: 1.0.0

logging:
  level:
    com:
      banking:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"