services:
    configserver:
        image: "senharshit03/configserver:img6"
        container_name: "configserver-ms"
        ports:
            - "8071:8071"
        healthcheck:
            test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        extends:
            file: common-config.yml
            service: microservice-base-config


    eurekaserver:
        image: "senharshit03/eurekaserver:img6"
        container_name: "eurekaserver_ms"
        ports:
            - "8070:8070"
        healthcheck:
            test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        extends:
            file: common-config.yml
            service: microservice-configserver-config
        environment:
            SPRING_APPLICATION_NAME: "eurekaserver"

    accounts:
        image: "senharshit03/accounts:img6"
        container_name: "accounts-ms"
        ports:
            - "8081:8081"
        healthcheck:
            test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: "accounts"
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config

    loans:
        image: "senharshit03/loans:img6"
        container_name: "loans-ms"
        ports:
            - "8090:8090"
        healthcheck:
            test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: "loans"
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config

    cards:
        image: "senharshit03/cards:img6"
        container_name: "cards-ms"
        ports:
            - "9000:9000"
        healthcheck:
            test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        environment:
            SPRING_APPLICATION_NAME: "cards"
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config

    gatewayserver:
        image: "senharshit03/gatewayserver:img6"
        container_name: gatewayserver-ms
        ports:
            - "8072:8072"
        depends_on:
            accounts:
                condition: service_healthy
            loans:
                condition: service_healthy
            cards:
                condition: service_healthy
        environment:
            SPRING_APPLICATION_NAME: "gatewayserver"
        extends:
            file: common-config.yml
            service: microservice-eurekaserver-config


networks:
    piggybank:
        driver: "bridge"